DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    LOCUS TEXT NOT NULL,
    SOURCE TEXT NOT NULL,
    TAXONOMY TEXT NOT NULL,
    GENOME_SIZE INTEGER NOT NULL,
    NUMBER_of_GENES INTEGER NOT  NULL,
    GC_content INTEGER NOT NULL,
    ORDONNE TEXT NOT NULL,
    ABSCISSE TEXT NOT NULL
);
